// SPDX-License-Identifier: AGPL-3.0-or-later
// Interface text. Error sentences and report wording come from @saucepenny/core (same as
// the CLI). Both catalogues must have the same keys (packages/web/test/strings.test.ts).

import type { Lang } from '@saucepenny/core';

const en = {
  'app.tagline': 'Free, offline recipe costing and menu pricing. Every number is checked twice.',
  'app.skip': 'Skip to the editor',
  'settings.lang': 'Language',
  'settings.theme': 'Theme',
  'settings.theme.system': 'System',
  'settings.theme.light': 'Light',
  'settings.theme.dark': 'Dark',
  'settings.large': 'Large text',
  'tab.ingredients': 'Ingredients',
  'tab.recipes': 'Recipes',
  'tab.menu': 'Menu',
  'tab.impact': 'Price change',
  'tab.data': 'Data & settings',
  'common.remove': 'Remove',
  'common.removeNamed': 'Remove {name}',
  'common.none': '—',
  'common.notVerified': 'not shown',
  'problems.title': 'Fix these to see costs:',
  'problems.more': '…and {n} more',
  'ing.title': 'Ingredients',
  'ing.help':
    'Enter what you pay for a pack. Usable yield % is what is left after trimming or peeling; it raises the real cost.',
  'ing.filter': 'Filter',
  'ing.name': 'Name',
  'ing.packQty': 'Pack size',
  'ing.unit': 'Unit',
  'ing.price': 'Price',
  'ing.yield': 'Usable %',
  'ing.density': 'Density g/ml',
  'ing.pieceWeight': 'g per piece',
  'ing.unitCost': 'Real cost',
  'ing.add': 'Add ingredient',
  'ing.new': 'New ingredient',
  'ing.inUse': '{name} is used by {recipes}; remove it there first.',
  'ing.count': '{n} ingredients',
  'ing.import': 'Import CSV',
  'ing.export': 'Export CSV',
  'ing.imported': 'Imported {n} ingredients.',
  'ing.importProblems': 'Some rows were not imported:',
  'rec.title': 'Recipes',
  'rec.add': 'Add recipe',
  'rec.new': 'New recipe',
  'rec.none': 'No recipes yet. Add one to start.',
  'rec.name': 'Recipe name',
  'rec.yieldQty': 'Makes',
  'rec.yieldUnit': 'Unit',
  'rec.density': 'Density g/ml (optional)',
  'rec.lines': 'Ingredients and sub-recipes',
  'rec.item': 'Item',
  'rec.qty': 'Amount',
  'rec.unit': 'Unit',
  'rec.waste': 'Waste %',
  'rec.cost': 'Cost',
  'rec.share': 'Share',
  'rec.addLine': 'Add line',
  'rec.ingredients': 'Ingredients',
  'rec.subRecipes': 'Sub-recipes',
  'rec.choose': '(choose)',
  'rec.total': 'Total cost',
  'rec.perUnit': 'Cost per {unit}',
  'rec.expand': 'Show {name}',
  'rec.inUse': '{name} is used by {users}; remove it there first.',
  'rec.remove': 'Remove recipe',
  'rec.scale': 'Scale',
  'rec.scaleTo': 'Make this amount instead',
  'rec.scaled': 'Scaled amount',
  'rec.scaledCost': 'Scaled cost',
  'rec.can': 'How much can I make?',
  'rec.canHave': 'I have',
  'rec.canOf': 'of',
  'rec.canResult': 'Enough for {qty} {unit}.',
  'rec.canUnused': 'This recipe does not use that ingredient.',
  'menu.title': 'Menu',
  'menu.help':
    'Food cost % = cost per portion ÷ price without service charge. Suggested prices are rounded up, so they never miss the target.',
  'menu.add': 'Add menu item',
  'menu.new': 'New dish',
  'menu.name': 'Dish',
  'menu.recipe': 'Recipe',
  'menu.portion': 'Portion',
  'menu.price': 'Price',
  'menu.service': 'Incl. service',
  'menu.target': 'Target %',
  'menu.rounding': 'Round up to',
  'menu.cost': 'Cost',
  'menu.foodCost': 'Food cost',
  'menu.suggested': 'Suggested',
  'menu.atSuggested': 'At suggested',
  'menu.profit': 'Gross profit',
  'menu.needRecipe': 'Add a recipe first.',
  'round.none': 'cent',
  'round.0.1': '0.1',
  'round.0.5': '0.5',
  'round.1': '1',
  'round.ending-8': 'ending in 8',
  'band.good': 'good',
  'band.watch': 'watch',
  'band.high': 'high',
  'impact.title': 'What if a price changes?',
  'impact.ingredient': 'Ingredient',
  'impact.price': 'New pack price',
  'impact.none': 'Nothing changes.',
  'impact.what': 'Recipe or dish',
  'impact.before': 'Before',
  'impact.after': 'After',
  'impact.change': 'Change',
  'impact.recipe': 'recipe (batch)',
  'impact.menu': 'dish (portion)',
  'impact.badPrice': 'Type a price of 0 or more.',
  'data.title': 'Project',
  'data.name': 'Project name',
  'data.currency': 'Currency (3 letters)',
  'data.service': 'Service charge %',
  'data.good': 'Good if food cost ≤ %',
  'data.high': 'High if food cost > %',
  'data.files': 'Files',
  'data.new': 'New empty project',
  'data.newConfirm': 'Replace the current project with an empty one?',
  'data.sample': 'Load the cha chaan teng example',
  'data.sampleConfirm': 'Replace the current project with the example?',
  'data.open': 'Open project (.json)',
  'data.save': 'Save project (.json)',
  'data.exportMenu': 'Menu costs (.csv)',
  'data.exportRecipes': 'Recipe costs (.csv)',
  'data.print': 'Print cost cards',
  'data.opened': 'Project opened.',
  'data.openFailed': 'Could not open the file:',
  'data.delete': 'Delete all data on this device',
  'data.deleteConfirm': 'Delete the project and settings stored in this browser?',
  'data.deleted': 'All data on this device was deleted.',
  'data.privacy':
    'Your project is saved only in this browser (IndexedDB). Nothing is uploaded. Save a .json file as a backup.',
  'print.title': 'Cost cards',
  'print.printed': '{date}',
  'status.saved': 'Saved in this browser.',
  'footer.privacy': 'Your data stays in this browser.',
  'footer.disclaimer': 'Estimates only, not accounting or tax advice.',
  'footer.affiliation': 'Independent project; not affiliated with any recipe-costing product.',
  'footer.source': 'Source code',
  'footer.licence': 'Licence: AGPL-3.0-or-later',
  'footer.coffee': 'Buy me a coffee',
} as const;

export type UiKey = keyof typeof en;

const zh: Record<UiKey, string> = {
  'app.tagline': '免費、離線的食譜成本及餐牌定價工具。每個數字都經兩次核對。',
  'app.skip': '跳到編輯區',
  'settings.lang': '語言',
  'settings.theme': '外觀',
  'settings.theme.system': '跟隨系統',
  'settings.theme.light': '淺色',
  'settings.theme.dark': '深色',
  'settings.large': '大字',
  'tab.ingredients': '食材',
  'tab.recipes': '食譜',
  'tab.menu': '餐牌',
  'tab.impact': '加價影響',
  'tab.data': '資料及設定',
  'common.remove': '刪除',
  'common.removeNamed': '刪除 {name}',
  'common.none': '—',
  'common.notVerified': '不顯示',
  'problems.title': '請先修正以下問題，才可計算成本：',
  'problems.more': '……另有 {n} 項',
  'ing.title': '食材',
  'ing.help': '輸入每包（每件）的入貨價。可用率是修剪或去皮後剩下的比例，會令實際成本提高。',
  'ing.filter': '篩選',
  'ing.name': '名稱',
  'ing.packQty': '包裝數量',
  'ing.unit': '單位',
  'ing.price': '價錢',
  'ing.yield': '可用率 %',
  'ing.density': '密度 克／毫升',
  'ing.pieceWeight': '每件克數',
  'ing.unitCost': '實際成本',
  'ing.add': '新增食材',
  'ing.new': '新食材',
  'ing.inUse': '「{name}」正被 {recipes} 使用，請先在那裏刪除。',
  'ing.count': '{n} 項食材',
  'ing.import': '匯入 CSV',
  'ing.export': '匯出 CSV',
  'ing.imported': '已匯入 {n} 項食材。',
  'ing.importProblems': '以下各行沒有匯入：',
  'rec.title': '食譜',
  'rec.add': '新增食譜',
  'rec.new': '新食譜',
  'rec.none': '未有食譜，請先新增。',
  'rec.name': '食譜名稱',
  'rec.yieldQty': '產出',
  'rec.yieldUnit': '單位',
  'rec.density': '密度 克／毫升（可選）',
  'rec.lines': '材料及子食譜',
  'rec.item': '項目',
  'rec.qty': '份量',
  'rec.unit': '單位',
  'rec.waste': '損耗 %',
  'rec.cost': '成本',
  'rec.share': '佔比',
  'rec.addLine': '新增一行',
  'rec.ingredients': '食材',
  'rec.subRecipes': '子食譜',
  'rec.choose': '（請選擇）',
  'rec.total': '總成本',
  'rec.perUnit': '每{unit}成本',
  'rec.expand': '展開「{name}」',
  'rec.inUse': '「{name}」正被 {users} 使用，請先在那裏刪除。',
  'rec.remove': '刪除食譜',
  'rec.scale': '按比例調整',
  'rec.scaleTo': '改為製作這個份量',
  'rec.scaled': '調整後份量',
  'rec.scaledCost': '調整後成本',
  'rec.can': '手上材料可以做多少？',
  'rec.canHave': '我有',
  'rec.canOf': '的',
  'rec.canResult': '足夠製作 {qty} {unit}。',
  'rec.canUnused': '這個食譜沒有用到該食材。',
  'menu.title': '餐牌',
  'menu.help': '食材成本率 = 每份成本 ÷ 不含服務費的售價。建議售價一律向上進位，所以不會超出目標。',
  'menu.add': '新增餐牌項目',
  'menu.new': '新菜式',
  'menu.name': '菜式',
  'menu.recipe': '食譜',
  'menu.portion': '每份',
  'menu.price': '售價',
  'menu.service': '已含服務費',
  'menu.target': '目標 %',
  'menu.rounding': '進位至',
  'menu.cost': '成本',
  'menu.foodCost': '食材成本率',
  'menu.suggested': '建議售價',
  'menu.atSuggested': '按建議售價',
  'menu.profit': '毛利',
  'menu.needRecipe': '請先新增食譜。',
  'round.none': '仙',
  'round.0.1': '一毫',
  'round.0.5': '五毫',
  'round.1': '一元',
  'round.ending-8': '尾數 8',
  'band.good': '良好',
  'band.watch': '留意',
  'band.high': '偏高',
  'impact.title': '如果食材加價？',
  'impact.ingredient': '食材',
  'impact.price': '新的每包價錢',
  'impact.none': '沒有任何改變。',
  'impact.what': '食譜或菜式',
  'impact.before': '之前',
  'impact.after': '之後',
  'impact.change': '變動',
  'impact.recipe': '食譜（每批）',
  'impact.menu': '菜式（每份）',
  'impact.badPrice': '請輸入 0 或以上的價錢。',
  'data.title': '項目',
  'data.name': '項目名稱',
  'data.currency': '貨幣（三個字母）',
  'data.service': '服務費 %',
  'data.good': '食材成本率 ≤ 此 % 為良好',
  'data.high': '食材成本率 > 此 % 為偏高',
  'data.files': '檔案',
  'data.new': '新的空白項目',
  'data.newConfirm': '以空白項目取代目前的項目？',
  'data.sample': '載入茶餐廳示範',
  'data.sampleConfirm': '以示範項目取代目前的項目？',
  'data.open': '開啟項目（.json）',
  'data.save': '儲存項目（.json）',
  'data.exportMenu': '餐牌成本（.csv）',
  'data.exportRecipes': '食譜成本（.csv）',
  'data.print': '列印成本卡',
  'data.opened': '已開啟項目。',
  'data.openFailed': '無法開啟檔案：',
  'data.delete': '刪除這部裝置上的所有資料',
  'data.deleteConfirm': '刪除這個瀏覽器內儲存的項目及設定？',
  'data.deleted': '已刪除這部裝置上的所有資料。',
  'data.privacy': '項目只儲存在這個瀏覽器（IndexedDB），不會上載。請另存 .json 檔作備份。',
  'print.title': '成本卡',
  'print.printed': '{date}',
  'status.saved': '已儲存在這個瀏覽器。',
  'footer.privacy': '資料只留在這個瀏覽器。',
  'footer.disclaimer': '只供估算，並非會計或稅務意見。',
  'footer.affiliation': '獨立項目，與任何食譜成本產品並無關連。',
  'footer.source': '原始碼',
  'footer.licence': '授權：AGPL-3.0-or-later',
  'footer.coffee': '請我喝杯咖啡',
};

export const catalogues: Record<Lang, Record<UiKey, string>> = { en, 'zh-HK': zh };

export function ui(lang: Lang, key: UiKey, params: Record<string, string | number> = {}): string {
  return catalogues[lang][key].replace(/\{(\w+)\}/g, (_, k: string) =>
    String(params[k] ?? `{${k}}`),
  );
}
